# PyTorch Basics
Tensor array library.

## Imports

In [2]:
import torch
import numpy as np

torch.__version__

'1.1.0'

## Tensors from NumPy Arrays
Generalized matrix (1-D, 2-D, 3-D, N-D).
- Scalar -> Single Value
- Vector -> 1D Tensor
- Matrix -> 2D Tensor
- Tensor -> 3D Tensor

In [3]:
arr = np.array([1,2,3,4,5])
type(arr)

numpy.ndarray

In [4]:
# Creates a direct link between the tensor and array (pass by reference).
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [5]:
# Creates a direct link between the tensor and array (pass by reference).
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [6]:
arr2d = np.arange(0.0,12.0).reshape(4,3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [8]:
# Arr not passed by reference and thus the preferred method.
torch.tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

## Tensors from Scratch

In [10]:
# Capital 'T'ensor is short-hand for float tensors.
torch.Tensor([1,2,3])

tensor([1., 2., 3.])

In [11]:
# Reserve memory for data later stored.
torch.empty(2,2)

tensor([[8.4486e+20, 6.4829e-10],
        [6.7377e-10, 0.0000e+00]])

In [14]:
torch.zeros(4,3, dtype=torch.int64)
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [15]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [16]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [18]:
t = torch.tensor([1,2,3])
t.dtype

torch.int64

In [19]:
# Change data type of tensors.
t = t.type(torch.int32)
t.dtype

torch.int32

In [21]:
# Random tensor values of a uniform dist 0 <-> 1.
torch.rand(4,3)

tensor([[0.9018, 0.2610, 0.2028],
        [0.0178, 0.3955, 0.5317],
        [0.7680, 0.3298, 0.2473],
        [0.3488, 0.4504, 0.4563]])

In [22]:
torch.randn(4,3)

tensor([[-0.1834,  0.2390, -0.4603],
        [-1.8286, -1.1987,  0.8087],
        [ 1.3522,  1.0109, -0.2794],
        [ 1.3868,  0.1487, -0.5769]])

In [23]:
# High is exclusive.
torch.randint(low=0, high=10, size=(4,3))

tensor([[7, 9, 4],
        [9, 1, 5],
        [6, 4, 5],
        [2, 6, 2]])

In [25]:
x = torch.zeros(2,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [26]:
# Produce a random tensor with the same shape as another tensor.
torch.rand_like(x)

tensor([[0.4623, 0.3534, 0.1583, 0.3428, 0.4077],
        [0.8156, 0.5135, 0.7946, 0.3295, 0.9431]])

In [27]:
torch.randn_like(x)

tensor([[ 0.0314,  0.9178,  0.8507, -1.8008, -3.3552],
        [-0.4936,  0.3345,  1.1540,  0.5350,  0.6391]])

In [28]:
torch.randint_like(x, low=0, high=11)

tensor([[ 5.,  7.,  1.,  9.,  8.],
        [10.,  9.,  5., 10.,  1.]])

In [36]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

## Tensors Ops

In [38]:
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [41]:
# Same indexers as NumPy.
x[:,1]

tensor([1, 3, 5])

In [42]:
x = torch.arange(10)

In [43]:
# Simply view as the following shape as opposed to reshape. A view also reflects the most recent data (by reference).
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [44]:
# If -1 is passed, PyTorch will infer the missing dimension.
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [46]:
a = torch.tensor([1.,2.,3.])
a.dtype

torch.float32

In [47]:
a + a

tensor([2., 4., 6.])

In [48]:
# Perform arithmetic operation without replacing original data. All arithmetic operations also have a _ suffix that performs inplace=True. I.e. a.add_(a)
a.add(a)

tensor([2., 4., 6.])

In [49]:
# Perform element-by-element multiplication (NOT matrix multiplication)
a * a

tensor([1., 4., 9.])

In [50]:
# Perform an actual matrix dot product.
a.dot(a)

tensor(14.)

In [55]:
# Performs an actual matrix multiplication.
a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[1,2],[3,4],[5,6]])
torch.mm(a, b)

tensor([[22, 28],
        [49, 64]])

In [56]:
# OR instead of .mm
a @ b

tensor([[22, 28],
        [49, 64]])