# PyTorch Basics
Tensor array library.

## Imports

In [1]:
import torch
import numpy as np

torch.__version__

'1.12.0'

## Tensors from NumPy Arrays
Generalized matrix (1-D, 2-D, 3-D, N-D).
- Scalar -> Single Value
- Vector -> 1D Tensor
- Matrix -> 2D Tensor
- Tensor -> 3D Tensor

In [2]:
arr = np.array([1,2,3,4,5])
type(arr)

numpy.ndarray

In [3]:
# Creates a direct link between the tensor and array (pass by reference).
torch.from_numpy(arr)

tensor([1, 2, 3, 4, 5])

In [4]:
# Creates a direct link between the tensor and array (pass by reference).
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5])

In [5]:
arr2d = np.arange(0.0,12.0).reshape(4,3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [6]:
# Arr not passed by reference and thus the preferred method.
torch.tensor(arr)

tensor([1, 2, 3, 4, 5])

## Tensors from Scratch

In [7]:
# Capital 'T'ensor is short-hand for float tensors.
torch.Tensor([1,2,3])

tensor([1., 2., 3.])

In [8]:
# Reserve memory for data later stored.
torch.empty(2,2)

tensor([[2.4148e-18, 2.2369e+08],
        [0.0000e+00, 0.0000e+00]])

In [9]:
torch.zeros(4,3, dtype=torch.int64)
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [11]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [12]:
t = torch.tensor([1,2,3])
t.dtype

torch.int64

In [13]:
# Change data type of tensors.
t = t.type(torch.int32)
t.dtype

torch.int32

In [14]:
# Random tensor values of a uniform dist 0 <-> 1.
torch.rand(4,3)

tensor([[0.6445, 0.3741, 0.0142],
        [0.4226, 0.8310, 0.2305],
        [0.1766, 0.9704, 0.9876],
        [0.5442, 0.2246, 0.0481]])

In [15]:
torch.randn(4,3)

tensor([[ 0.5639, -0.4756,  1.3070],
        [-1.6050,  0.3589,  3.2647],
        [-0.6848, -1.4629,  1.0417],
        [-1.0134,  1.3025, -0.8693]])

In [16]:
# High is exclusive.
torch.randint(low=0, high=10, size=(4,3))

tensor([[2, 0, 6],
        [0, 9, 2],
        [1, 7, 7],
        [2, 3, 1]])

In [17]:
x = torch.zeros(2,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [18]:
# Produce a random tensor with the same shape as another tensor.
torch.rand_like(x)

tensor([[0.7279, 0.8364, 0.5077, 0.8832, 0.2490],
        [0.3538, 0.6547, 0.0846, 0.5825, 0.1760]])

In [19]:
torch.randn_like(x)

tensor([[-0.3789,  0.8310,  0.2875, -0.0185,  0.5026],
        [ 0.2807, -1.1832,  1.6764,  0.2929, -1.4905]])

In [20]:
torch.randint_like(x, low=0, high=11)

tensor([[ 4.,  4.,  0.,  1.,  6.],
        [ 4.,  3.,  9.,  6., 10.]])

In [21]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

## Tensors Ops

In [22]:
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [23]:
# Same indexers as NumPy.
x[:,1]

tensor([1, 3, 5])

In [24]:
x = torch.arange(10)

In [25]:
# Simply view as the following shape as opposed to reshape. A view also reflects the most recent data (by reference).
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [26]:
# If -1 is passed, PyTorch will infer the missing dimension.
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [27]:
a = torch.tensor([1.,2.,3.])
a.dtype

torch.float32

In [28]:
a + a

tensor([2., 4., 6.])

In [29]:
# Perform arithmetic operation without replacing original data. All arithmetic operations also have a _ suffix that performs inplace=True. I.e. a.add_(a)
a.add(a)

tensor([2., 4., 6.])

In [30]:
# Perform element-by-element multiplication (NOT matrix multiplication)
a * a

tensor([1., 4., 9.])

In [31]:
# Perform an actual matrix dot product.
a.dot(a)

tensor(14.)

In [32]:
# Performs an actual matrix multiplication.
a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[1,2],[3,4],[5,6]])
torch.mm(a, b)

tensor([[22, 28],
        [49, 64]])

In [33]:
# OR instead of .mm
a @ b

tensor([[22, 28],
        [49, 64]])