# Import

In [16]:
import torch

# Gradients

In [17]:
# Set up computational tracking on the tensor.
x = torch.tensor(2., requires_grad=True)

In [18]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
y

tensor(63., grad_fn=<AddBackward0>)

In [19]:
# Back propagation.
y.backward()

In [20]:
x.grad

tensor(93.)

In [22]:
x = torch.tensor([[1.,2.,3.],[3.,2.,1.]], requires_grad=True)
x

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)

In [24]:
y = 3*x + 2
y

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)

In [25]:
z = 2*y**2
z

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)

In [26]:
out = z.mean()
out

tensor(140., grad_fn=<MeanBackward0>)

In [27]:
# find gradient of x with respect to out.
out.backward()
x.grad

tensor([[10., 16., 22.],
        [22., 16., 10.]])